application: debsankha-manik
version: 1
runtime: python
api_version: 1

handlers:
- url: /stat
  script: stat.py

- url: /_ah/xmpp/message/chat/
  script: stat.py

- url: /others
  script: others.py

- url: /
  static_dir: static



inbound_services:
- xmpp_message
