application: debsankha-manik
version: 1
runtime: python
api_version: 1

handlers:
- url: /stat
  script: info.py

- url: /_ah/xmpp/message/chat/
  script: info.py

- url: /others
  script: others.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /misc/(.*)
  static_files: static/misc/\1
  upload: static/misc/(.*)

- url: /
  static_dir: static



inbound_services:
- xmpp_message
